// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qpahynondwttnedmfhkv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFwYWh5bm9uZHd0dG5lZG1maGt2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3MTEwOTYsImV4cCI6MjA2MTI4NzA5Nn0.c3vCYqzNbDxCE_hUEC-8HCgL6Rb8n7vWTthj7Nho9fA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);